def forward_256(self,
    token_single_input_feats: Tensor,
    token_pair_input_feats: Tensor,
    atom_single_input_feats: Tensor,
    block_atom_pair_feat: Tensor,
    block_atom_pair_mask: Tensor,
    block_indices_h: Tensor,
    block_indices_w: Tensor,
    atom_single_mask: Tensor,
    atom_token_indices: Tensor) -> Tuple[Tensor, Tensor, Tensor]:
  token_pair_proj_in_trunk = self.token_pair_proj_in_trunk
  token_single_to_token_pair_outer_sum_proj = self.token_single_to_token_pair_outer_sum_proj
  token_single_proj_in_trunk = self.token_single_proj_in_trunk
  token_single_proj_in_structure = self.token_single_proj_in_structure
  token_single_input_emb = self.token_single_input_emb
  atom_encoder = token_single_input_emb.atom_encoder
  to_token_single = atom_encoder.to_token_single
  token_single_input_emb0 = self.token_single_input_emb
  atom_encoder0 = token_single_input_emb0.atom_encoder
  atom_transformer = atom_encoder0.atom_transformer
  local_diffn_transformer = atom_transformer.local_diffn_transformer
  transitions = local_diffn_transformer.transitions
  _2 = getattr(transitions, "2")
  linear_b_nobias = _2.linear_b_nobias
  token_single_input_emb1 = self.token_single_input_emb
  atom_encoder1 = token_single_input_emb1.atom_encoder
  atom_transformer0 = atom_encoder1.atom_transformer
  local_diffn_transformer0 = atom_transformer0.local_diffn_transformer
  transitions0 = local_diffn_transformer0.transitions
  _20 = getattr(transitions0, "2")
  linear_s_biasinit_m2 = _20.linear_s_biasinit_m2
  token_single_input_emb2 = self.token_single_input_emb
  atom_encoder2 = token_single_input_emb2.atom_encoder
  atom_transformer1 = atom_encoder2.atom_transformer
  local_diffn_transformer1 = atom_transformer1.local_diffn_transformer
  transitions1 = local_diffn_transformer1.transitions
  _21 = getattr(transitions1, "2")
  linear_a_nobias_double = _21.linear_a_nobias_double
  token_single_input_emb3 = self.token_single_input_emb
  atom_encoder3 = token_single_input_emb3.atom_encoder
  atom_transformer2 = atom_encoder3.atom_transformer
  local_diffn_transformer2 = atom_transformer2.local_diffn_transformer
  transitions2 = local_diffn_transformer2.transitions
  _22 = getattr(transitions2, "2")
  ada_ln = _22.ada_ln
  lin_s_merged = ada_ln.lin_s_merged
  token_single_input_emb4 = self.token_single_input_emb
  atom_encoder4 = token_single_input_emb4.atom_encoder
  atom_transformer3 = atom_encoder4.atom_transformer
  local_diffn_transformer3 = atom_transformer3.local_diffn_transformer
  local_attentions = local_diffn_transformer3.local_attentions
  _23 = getattr(local_attentions, "2")
  out_proj = _23.out_proj
  token_single_input_emb5 = self.token_single_input_emb
  atom_encoder5 = token_single_input_emb5.atom_encoder
  atom_transformer4 = atom_encoder5.atom_transformer
  local_diffn_transformer4 = atom_transformer4.local_diffn_transformer
  local_attentions0 = local_diffn_transformer4.local_attentions
  _24 = getattr(local_attentions0, "2")
  q_bias = _24.q_bias
  token_single_input_emb6 = self.token_single_input_emb
  atom_encoder6 = token_single_input_emb6.atom_encoder
  atom_transformer5 = atom_encoder6.atom_transformer
  local_diffn_transformer5 = atom_transformer5.local_diffn_transformer
  local_attentions1 = local_diffn_transformer5.local_attentions
  _25 = getattr(local_attentions1, "2")
  to_qkv = _25.to_qkv
  token_single_input_emb7 = self.token_single_input_emb
  atom_encoder7 = token_single_input_emb7.atom_encoder
  atom_transformer6 = atom_encoder7.atom_transformer
  local_diffn_transformer6 = atom_transformer6.local_diffn_transformer
  local_attentions2 = local_diffn_transformer6.local_attentions
  _26 = getattr(local_attentions2, "2")
  single_layer_norm = _26.single_layer_norm
  lin_s_merged0 = single_layer_norm.lin_s_merged
  token_single_input_emb8 = self.token_single_input_emb
  atom_encoder8 = token_single_input_emb8.atom_encoder
  atom_transformer7 = atom_encoder8.atom_transformer
  local_diffn_transformer7 = atom_transformer7.local_diffn_transformer
  transitions3 = local_diffn_transformer7.transitions
  _1 = getattr(transitions3, "1")
  linear_b_nobias0 = _1.linear_b_nobias
  token_single_input_emb9 = self.token_single_input_emb
  atom_encoder9 = token_single_input_emb9.atom_encoder
  atom_transformer8 = atom_encoder9.atom_transformer
  local_diffn_transformer8 = atom_transformer8.local_diffn_transformer
  transitions4 = local_diffn_transformer8.transitions
  _10 = getattr(transitions4, "1")
  linear_s_biasinit_m20 = _10.linear_s_biasinit_m2
  token_single_input_emb10 = self.token_single_input_emb
  atom_encoder10 = token_single_input_emb10.atom_encoder
  atom_transformer9 = atom_encoder10.atom_transformer
  local_diffn_transformer9 = atom_transformer9.local_diffn_transformer
  transitions5 = local_diffn_transformer9.transitions
  _11 = getattr(transitions5, "1")
  linear_a_nobias_double0 = _11.linear_a_nobias_double
  token_single_input_emb11 = self.token_single_input_emb
  atom_encoder11 = token_single_input_emb11.atom_encoder
  atom_transformer10 = atom_encoder11.atom_transformer
  local_diffn_transformer10 = atom_transformer10.local_diffn_transformer
  transitions6 = local_diffn_transformer10.transitions
  _12 = getattr(transitions6, "1")
  ada_ln0 = _12.ada_ln
  lin_s_merged1 = ada_ln0.lin_s_merged
  token_single_input_emb12 = self.token_single_input_emb
  atom_encoder12 = token_single_input_emb12.atom_encoder
  atom_transformer11 = atom_encoder12.atom_transformer
  local_diffn_transformer11 = atom_transformer11.local_diffn_transformer
  local_attentions3 = local_diffn_transformer11.local_attentions
  _13 = getattr(local_attentions3, "1")
  out_proj0 = _13.out_proj
  token_single_input_emb13 = self.token_single_input_emb
  atom_encoder13 = token_single_input_emb13.atom_encoder
  atom_transformer12 = atom_encoder13.atom_transformer
  local_diffn_transformer12 = atom_transformer12.local_diffn_transformer
  local_attentions4 = local_diffn_transformer12.local_attentions
  _14 = getattr(local_attentions4, "1")
  q_bias0 = _14.q_bias
  token_single_input_emb14 = self.token_single_input_emb
  atom_encoder14 = token_single_input_emb14.atom_encoder
  atom_transformer13 = atom_encoder14.atom_transformer
  local_diffn_transformer13 = atom_transformer13.local_diffn_transformer
  local_attentions5 = local_diffn_transformer13.local_attentions
  _15 = getattr(local_attentions5, "1")
  to_qkv0 = _15.to_qkv
  token_single_input_emb15 = self.token_single_input_emb
  atom_encoder15 = token_single_input_emb15.atom_encoder
  atom_transformer14 = atom_encoder15.atom_transformer
  local_diffn_transformer14 = atom_transformer14.local_diffn_transformer
  local_attentions6 = local_diffn_transformer14.local_attentions
  _16 = getattr(local_attentions6, "1")
  single_layer_norm0 = _16.single_layer_norm
  lin_s_merged2 = single_layer_norm0.lin_s_merged
  token_single_input_emb16 = self.token_single_input_emb
  atom_encoder16 = token_single_input_emb16.atom_encoder
  atom_transformer15 = atom_encoder16.atom_transformer
  local_diffn_transformer15 = atom_transformer15.local_diffn_transformer
  transitions7 = local_diffn_transformer15.transitions
  _0 = getattr(transitions7, "0")
  linear_b_nobias1 = _0.linear_b_nobias
  token_single_input_emb17 = self.token_single_input_emb
  atom_encoder17 = token_single_input_emb17.atom_encoder
  atom_transformer16 = atom_encoder17.atom_transformer
  local_diffn_transformer16 = atom_transformer16.local_diffn_transformer
  transitions8 = local_diffn_transformer16.transitions
  _00 = getattr(transitions8, "0")
  linear_s_biasinit_m21 = _00.linear_s_biasinit_m2
  token_single_input_emb18 = self.token_single_input_emb
  atom_encoder18 = token_single_input_emb18.atom_encoder
  atom_transformer17 = atom_encoder18.atom_transformer
  local_diffn_transformer17 = atom_transformer17.local_diffn_transformer
  transitions9 = local_diffn_transformer17.transitions
  _01 = getattr(transitions9, "0")
  linear_a_nobias_double1 = _01.linear_a_nobias_double
  token_single_input_emb19 = self.token_single_input_emb
  atom_encoder19 = token_single_input_emb19.atom_encoder
  atom_transformer18 = atom_encoder19.atom_transformer
  local_diffn_transformer18 = atom_transformer18.local_diffn_transformer
  transitions10 = local_diffn_transformer18.transitions
  _02 = getattr(transitions10, "0")
  ada_ln1 = _02.ada_ln
  lin_s_merged3 = ada_ln1.lin_s_merged
  token_single_input_emb20 = self.token_single_input_emb
  atom_encoder20 = token_single_input_emb20.atom_encoder
  atom_transformer19 = atom_encoder20.atom_transformer
  local_diffn_transformer19 = atom_transformer19.local_diffn_transformer
  local_attentions7 = local_diffn_transformer19.local_attentions
  _03 = getattr(local_attentions7, "0")
  out_proj1 = _03.out_proj
  token_single_input_emb21 = self.token_single_input_emb
  atom_encoder21 = token_single_input_emb21.atom_encoder
  atom_transformer20 = atom_encoder21.atom_transformer
  local_diffn_transformer20 = atom_transformer20.local_diffn_transformer
  local_attentions8 = local_diffn_transformer20.local_attentions
  _04 = getattr(local_attentions8, "0")
  q_bias1 = _04.q_bias
  token_single_input_emb22 = self.token_single_input_emb
  atom_encoder22 = token_single_input_emb22.atom_encoder
  atom_transformer21 = atom_encoder22.atom_transformer
  local_diffn_transformer21 = atom_transformer21.local_diffn_transformer
  local_attentions9 = local_diffn_transformer21.local_attentions
  _05 = getattr(local_attentions9, "0")
  to_qkv1 = _05.to_qkv
  token_single_input_emb23 = self.token_single_input_emb
  atom_encoder23 = token_single_input_emb23.atom_encoder
  atom_transformer22 = atom_encoder23.atom_transformer
  local_diffn_transformer22 = atom_transformer22.local_diffn_transformer
  local_attentions10 = local_diffn_transformer22.local_attentions
  _06 = getattr(local_attentions10, "0")
  single_layer_norm1 = _06.single_layer_norm
  lin_s_merged4 = single_layer_norm1.lin_s_merged
  token_single_input_emb24 = self.token_single_input_emb
  atom_encoder24 = token_single_input_emb24.atom_encoder
  atom_transformer23 = atom_encoder24.atom_transformer
  local_diffn_transformer23 = atom_transformer23.local_diffn_transformer
  blocked_pairs2blocked_bias = local_diffn_transformer23.blocked_pairs2blocked_bias
  _17 = getattr(blocked_pairs2blocked_bias, "1")
  weight = _17.weight
  token_single_input_emb25 = self.token_single_input_emb
  atom_encoder25 = token_single_input_emb25.atom_encoder
  atom_transformer24 = atom_encoder25.atom_transformer
  local_diffn_transformer24 = atom_transformer24.local_diffn_transformer
  blocked_pairs2blocked_bias0 = local_diffn_transformer24.blocked_pairs2blocked_bias
  _07 = getattr(blocked_pairs2blocked_bias0, "0")
  token_single_input_emb26 = self.token_single_input_emb
  atom_encoder26 = token_single_input_emb26.atom_encoder
  pair_update_block = atom_encoder26.pair_update_block
  token_single_input_emb27 = self.token_single_input_emb
  atom_encoder27 = token_single_input_emb27.atom_encoder
  to_atom_cond = atom_encoder27.to_atom_cond
  _8 = torch.size(token_single_input_feats, 1)
  num_tokens = ops.prim.NumToTensor(_8)
  _9 = int(num_tokens)
  _7 = int(num_tokens)
  _3 = (to_atom_cond).forward(atom_single_input_feats, )
  x = torch.unsqueeze(_3, 1)
  atom_single_repr = torch.expand(x, [-1, 1, -1, -1])
  _4 = ops.prim.NumToTensor(torch.size(_3, 2))
  _5 = int(_4)
  x0 = torch.layer_norm(torch.to(_3, 6), [_5])
  x1 = torch.contiguous(atom_single_repr)
  x2 = torch.unsqueeze(x0, 1)
  atom_single_cond_repr = torch.expand(x2, [-1, 1, -1, -1])
  _6 = torch.slice(atom_single_cond_repr, 0, 0, 9223372036854775807)
  _18 = torch.slice(_6, 1, 0, 9223372036854775807)
  _19 = annotate(List[Optional[Tensor]], [None, None, block_indices_h])
  input = torch.index(_18, _19)
  _27 = torch.slice(atom_single_cond_repr, 0, 0, 9223372036854775807)
  _28 = torch.slice(_27, 1, 0, 9223372036854775807)
  _29 = annotate(List[Optional[Tensor]], [None, None, block_indices_w])
  input0 = torch.index(_28, _29)
  _30 = (pair_update_block).forward(input, input0, block_atom_pair_feat, )
  element = ops.prim.NumToTensor(torch.size(x1, 0))
  element0 = ops.prim.NumToTensor(torch.size(x1, 1))
  element1 = ops.prim.NumToTensor(torch.size(x1, 2))
  element2 = ops.prim.NumToTensor(torch.size(x1, 3))
  result = torch.mul(element, CONSTANTS.c0)
  _31 = int(torch.mul_(result, element0))
  _32 = int(torch.mul(element1, CONSTANTS.c0))
  _33 = int(torch.mul(element2, CONSTANTS.c0))
  single_repr = torch.reshape(x1, [_31, _32, _33])
  element3 = ops.prim.NumToTensor(torch.size(x0, 0))
  element4 = ops.prim.NumToTensor(torch.size(x0, 1))
  element5 = ops.prim.NumToTensor(torch.size(x0, 2))
  result0 = torch.mul(element3, CONSTANTS.c0)
  _34 = int(torch.mul_(result0, CONSTANTS.c0))
  _35 = int(torch.mul(element4, CONSTANTS.c0))
  _36 = int(torch.mul(element5, CONSTANTS.c0))
  x3 = torch.unsqueeze(x0, 1)
  x4 = torch.expand(x3, [-1, 1, -1, -1])
  input1 = torch.reshape(x4, [_34, _35, _36])
  element6 = ops.prim.NumToTensor(torch.size(_30, 0))
  element7 = ops.prim.NumToTensor(torch.size(_30, 1))
  element8 = ops.prim.NumToTensor(torch.size(_30, 2))
  element9 = ops.prim.NumToTensor(torch.size(_30, 3))
  element10 = ops.prim.NumToTensor(torch.size(_30, 4))
  element11 = ops.prim.NumToTensor(torch.size(_30, 5))
  result1 = torch.mul(element6, CONSTANTS.c0)
  _37 = int(torch.mul_(result1, element7))
  _38 = int(torch.mul(element8, CONSTANTS.c0))
  _39 = int(torch.mul(element9, CONSTANTS.c0))
  _40 = int(torch.mul(element10, CONSTANTS.c0))
  _41 = int(torch.mul(element11, CONSTANTS.c0))
  input2 = torch.reshape(_30, [_37, _38, _39, _40, _41])
  element12 = ops.prim.NumToTensor(torch.size(block_atom_pair_mask, 0))
  element13 = ops.prim.NumToTensor(torch.size(block_atom_pair_mask, 1))
  element14 = ops.prim.NumToTensor(torch.size(block_atom_pair_mask, 2))
  element15 = ops.prim.NumToTensor(torch.size(block_atom_pair_mask, 3))
  result2 = torch.mul(element12, CONSTANTS.c0)
  _42 = int(torch.mul_(result2, CONSTANTS.c0))
  _43 = int(torch.mul(element13, CONSTANTS.c0))
  _44 = int(torch.mul(element14, CONSTANTS.c0))
  _45 = int(torch.mul(element15, CONSTANTS.c0))
  x5 = torch.unsqueeze(block_atom_pair_mask, 1)
  x6 = torch.expand(x5, [-1, 1, -1, -1, -1])
  block_pair_mask = torch.reshape(x6, [_42, _43, _44, _45])
  element16 = ops.prim.NumToTensor(torch.size(atom_single_mask, 0))
  element17 = ops.prim.NumToTensor(torch.size(atom_single_mask, 1))
  result3 = torch.mul(element16, CONSTANTS.c0)
  _46 = int(torch.mul_(result3, CONSTANTS.c0))
  _47 = int(torch.mul(element17, CONSTANTS.c0))
  x7 = torch.unsqueeze(atom_single_mask, 1)
  x8 = torch.expand(x7, [-1, 1, -1])
  single_mask = torch.reshape(x8, [_46, _47])
  other = ops.prim.NumToTensor(torch.size(block_pair_mask, 2))
  _48 = int(other)
  kv_block_size = ops.prim.NumToTensor(torch.size(block_pair_mask, 3))
  _49 = annotate(number, kv_block_size)
  _50 = int(kv_block_size)
  sequence_length = ops.prim.NumToTensor(torch.size(single_repr, 1))
  _51 = annotate(number, sequence_length)
  _52 = int(sequence_length)
  num_blocks = torch.floor_divide(sequence_length, other)
  _53 = int(num_blocks)
  out = torch.new_empty(single_repr, [_52], dtype=4, layout=None, device=None, pin_memory=False)
  x9 = torch.arange(0, _51, out=out)
  q_indices = torch.reshape(x9, [_53, _48])
  _54 = torch.slice(q_indices, 0, 0, 9223372036854775807)
  _55 = torch.slice(_54, 1, 0, 1)
  _56 = torch.floor_divide(torch.sub(other, kv_block_size), CONSTANTS.c1)
  kv_indices = torch.add(_55, _56)
  out0 = torch.new_empty(single_repr, [_50], dtype=4, layout=None, device=None, pin_memory=False)
  kv_indices0 = torch.add(kv_indices, torch.arange(0, _49, out=out0))
  kv_idx = torch.remainder(kv_indices0, sequence_length)
  _57 = (_07).forward(input2, )
  _58, _59, _60, = torch.unbind(weight)
  _61 = torch.bitwise_not(torch.unsqueeze(single_mask, -1))
  single_repr0 = torch.masked_fill(single_repr, _61, 0.)
  _62 = [torch.to(_57, 15), torch.to(_58, 15)]
  value = torch.einsum("b l q k c, h c -> b h l q k", _62)
  element18 = ops.prim.NumToTensor(torch.size(block_pair_mask, 0))
  element19 = ops.prim.NumToTensor(torch.size(block_pair_mask, 1))
  element20 = ops.prim.NumToTensor(torch.size(block_pair_mask, 2))
  element21 = ops.prim.NumToTensor(torch.size(block_pair_mask, 3))
  _63 = int(torch.mul(element18, CONSTANTS.c0))
  _64 = int(torch.mul(element19, CONSTANTS.c0))
  _65 = int(torch.mul(element20, CONSTANTS.c0))
  _66 = int(torch.mul(element21, CONSTANTS.c0))
  mask = torch.reshape(block_pair_mask, [_63, 1, _64, _65, _66])
  blocked_pair_bias = torch.masked_fill(value, torch.bitwise_not(mask), -10000)
  _67 = ops.prim.NumToTensor(torch.size(single_repr0, 2))
  _68 = int(_67)
  feat_repr = torch.layer_norm(torch.to(single_repr0, 6), [_68], None, None, 0.10000000000000001)
  _69 = torch.chunk((lin_s_merged4).forward(input1, ), 2, -1)
  scale, shift, = _69
  _70 = torch.mul(feat_repr, torch.add(scale, CONSTANTS.c0))
  _71 = torch.add(_70, shift)
  element22 = ops.prim.NumToTensor(torch.size(blocked_pair_bias, 0))
  _72 = int(element22)
  _73 = int(element22)
  dim = ops.prim.NumToTensor(torch.size(blocked_pair_bias, 1))
  _74 = torch.unbind((to_qkv1).forward(_71, ))
  q, k, v, = _74
  element23 = ops.prim.NumToTensor(torch.size(q_bias1, 1))
  result4 = torch.mul(element22, CONSTANTS.c0)
  _75 = int(torch.mul_(result4, dim))
  _76 = int(torch.mul(element23, CONSTANTS.c0))
  x10 = torch.unsqueeze(q_bias1, 0)
  x11 = torch.expand(x10, [_73, -1, -1])
  x12 = torch.add(q, torch.reshape(x11, [_75, 1, _76]))
  element24 = ops.prim.NumToTensor(torch.size(blocked_pair_bias, 2))
  _77 = int(element24)
  dim0 = ops.prim.NumToTensor(torch.size(blocked_pair_bias, 3))
  _78 = int(dim0)
  element25 = ops.prim.NumToTensor(torch.size(x12, 0))
  _79 = int(element25)
  element26 = ops.prim.NumToTensor(torch.size(x12, 2))
  q0 = torch.reshape(x12, [_79, _77, _78, int(element26)])
  _80 = torch.slice(k, 0, 0, 9223372036854775807)
  _81 = torch.slice(_80, 2, 0, 9223372036854775807)
  _82 = annotate(List[Optional[Tensor]], [None, kv_idx])
  k0 = torch.index(_81, _82)
  _83 = torch.slice(v, 0, 0, 9223372036854775807)
  _84 = torch.slice(_83, 2, 0, 9223372036854775807)
  _85 = annotate(List[Optional[Tensor]], [None, kv_idx])
  v0 = torch.index(_84, _85)
  element27 = ops.prim.NumToTensor(torch.size(blocked_pair_bias, 0))
  element28 = ops.prim.NumToTensor(torch.size(blocked_pair_bias, 1))
  element29 = ops.prim.NumToTensor(torch.size(blocked_pair_bias, 2))
  element30 = ops.prim.NumToTensor(torch.size(blocked_pair_bias, 3))
  element31 = ops.prim.NumToTensor(torch.size(blocked_pair_bias, 4))
  result5 = torch.mul(element27, CONSTANTS.c0)
  _86 = int(torch.mul_(result5, element28))
  _87 = int(torch.mul(element29, CONSTANTS.c0))
  _88 = int(torch.mul(element30, CONSTANTS.c0))
  _89 = int(torch.mul(element31, CONSTANTS.c0))
  attn_mask = torch.reshape(blocked_pair_bias, [_86, _87, _88, _89])
  x13 = torch.scaled_dot_product_attention(torch.to(q0, 15), k0, v0, attn_mask)
  _90 = ops.prim.NumToTensor(torch.size(x13, 0))
  element32 = ops.prim.NumToTensor(torch.size(x13, 1))
  _91 = int(element32)
  element33 = ops.prim.NumToTensor(torch.size(x13, 2))
  _92 = int(element33)
  element34 = ops.prim.NumToTensor(torch.size(x13, 3))
  _93 = int(element34)
  other0 = torch.mul(element22, CONSTANTS.c0)
  element35 = torch.floor_divide(_90, other0)
  _94 = int(element35)
  _95 = int(torch.mul(element22, CONSTANTS.c0))
  result6 = torch.mul(element32, CONSTANTS.c0)
  _96 = int(torch.mul_(result6, element33))
  result7 = torch.mul(element35, CONSTANTS.c0)
  _97 = int(torch.mul_(result7, element34))
  x14 = torch.reshape(x13, [_72, _94, _91, _92, _93])
  x15 = torch.permute(x14, [0, 2, 3, 1, 4])
  out1 = torch.reshape(x15, [_95, _96, _97])
  gate = torch.sigmoid_((out_proj1).forward(input1, ))
  feat_local_added = torch.mul(out1, gate)
  _98 = ops.prim.NumToTensor(torch.size(single_repr0, 2))
  _99 = int(_98)
  feat_repr0 = torch.layer_norm(torch.to(single_repr0, 6), [_99], None, None, 0.10000000000000001)
  _100 = torch.chunk((lin_s_merged3).forward(input1, ), 2, -1)
  scale0, shift0, = _100
  _101 = torch.mul(feat_repr0, torch.add(scale0, CONSTANTS.c0))
  input3 = torch.add(_101, shift0)
  _102 = (linear_a_nobias_double1).forward(input3, )
  input4, a2, = torch.chunk(_102, 2, -1)
  input5 = torch.mul(torch.silu(input4), a2)
  _103 = (linear_s_biasinit_m21).forward(input1, )
  feat_trans_added = torch.mul(torch.sigmoid(_103), (linear_b_nobias1).forward(input5, ))
  _104 = torch.add(single_repr0, feat_trans_added)
  single_repr1 = torch.add(_104, feat_local_added)
  _105 = torch.bitwise_not(torch.unsqueeze(single_mask, -1))
  single_repr2 = torch.masked_fill(single_repr1, _105, 0.)
  _106 = [torch.to(_57, 15), torch.to(_59, 15)]
  value0 = torch.einsum("b l q k c, h c -> b h l q k", _106)
  element36 = ops.prim.NumToTensor(torch.size(block_pair_mask, 0))
  element37 = ops.prim.NumToTensor(torch.size(block_pair_mask, 1))
  element38 = ops.prim.NumToTensor(torch.size(block_pair_mask, 2))
  element39 = ops.prim.NumToTensor(torch.size(block_pair_mask, 3))
  _107 = int(torch.mul(element36, CONSTANTS.c0))
  _108 = int(torch.mul(element37, CONSTANTS.c0))
  _109 = int(torch.mul(element38, CONSTANTS.c0))
  _110 = int(torch.mul(element39, CONSTANTS.c0))
  mask0 = torch.reshape(block_pair_mask, [_107, 1, _108, _109, _110])
  blocked_pair_bias0 = torch.masked_fill(value0, torch.bitwise_not(mask0), -10000)
  _111 = ops.prim.NumToTensor(torch.size(single_repr2, 2))
  _112 = int(_111)
  feat_repr1 = torch.layer_norm(torch.to(single_repr2, 6), [_112], None, None, 0.10000000000000001)
  _113 = torch.chunk((lin_s_merged2).forward(input1, ), 2, -1)
  scale1, shift1, = _113
  _114 = torch.mul(feat_repr1, torch.add(scale1, CONSTANTS.c0))
  _115 = torch.add(_114, shift1)
  element40 = ops.prim.NumToTensor(torch.size(blocked_pair_bias0, 0))
  _116 = int(element40)
  _117 = int(element40)
  dim1 = ops.prim.NumToTensor(torch.size(blocked_pair_bias0, 1))
  _118 = torch.unbind((to_qkv0).forward(_115, ))
  q1, k1, v1, = _118
  element41 = ops.prim.NumToTensor(torch.size(q_bias0, 1))
  result8 = torch.mul(element40, CONSTANTS.c0)
  _119 = int(torch.mul_(result8, dim1))
  _120 = int(torch.mul(element41, CONSTANTS.c0))
  x16 = torch.unsqueeze(q_bias0, 0)
  x17 = torch.expand(x16, [_117, -1, -1])
  x18 = torch.add(q1, torch.reshape(x17, [_119, 1, _120]))
  element42 = ops.prim.NumToTensor(torch.size(blocked_pair_bias0, 2))
  _121 = int(element42)
  dim2 = ops.prim.NumToTensor(torch.size(blocked_pair_bias0, 3))
  _122 = int(dim2)
  element43 = ops.prim.NumToTensor(torch.size(x18, 0))
  _123 = int(element43)
  element44 = ops.prim.NumToTensor(torch.size(x18, 2))
  q2 = torch.reshape(x18, [_123, _121, _122, int(element44)])
  _124 = torch.slice(k1, 0, 0, 9223372036854775807)
  _125 = torch.slice(_124, 2, 0, 9223372036854775807)
  _126 = annotate(List[Optional[Tensor]], [None, kv_idx])
  k2 = torch.index(_125, _126)
  _127 = torch.slice(v1, 0, 0, 9223372036854775807)
  _128 = torch.slice(_127, 2, 0, 9223372036854775807)
  _129 = annotate(List[Optional[Tensor]], [None, kv_idx])
  v2 = torch.index(_128, _129)
  element45 = ops.prim.NumToTensor(torch.size(blocked_pair_bias0, 0))
  element46 = ops.prim.NumToTensor(torch.size(blocked_pair_bias0, 1))
  element47 = ops.prim.NumToTensor(torch.size(blocked_pair_bias0, 2))
  element48 = ops.prim.NumToTensor(torch.size(blocked_pair_bias0, 3))
  element49 = ops.prim.NumToTensor(torch.size(blocked_pair_bias0, 4))
  result9 = torch.mul(element45, CONSTANTS.c0)
  _130 = int(torch.mul_(result9, element46))
  _131 = int(torch.mul(element47, CONSTANTS.c0))
  _132 = int(torch.mul(element48, CONSTANTS.c0))
  _133 = int(torch.mul(element49, CONSTANTS.c0))
  attn_mask0 = torch.reshape(blocked_pair_bias0, [_130, _131, _132, _133])
  x19 = torch.scaled_dot_product_attention(torch.to(q2, 15), k2, v2, attn_mask0)
  _134 = ops.prim.NumToTensor(torch.size(x19, 0))
  element50 = ops.prim.NumToTensor(torch.size(x19, 1))
  _135 = int(element50)
  element51 = ops.prim.NumToTensor(torch.size(x19, 2))
  _136 = int(element51)
  element52 = ops.prim.NumToTensor(torch.size(x19, 3))
  _137 = int(element52)
  other1 = torch.mul(element40, CONSTANTS.c0)
  element53 = torch.floor_divide(_134, other1)
  _138 = int(element53)
  _139 = int(torch.mul(element40, CONSTANTS.c0))
  result10 = torch.mul(element50, CONSTANTS.c0)
  _140 = int(torch.mul_(result10, element51))
  result11 = torch.mul(element53, CONSTANTS.c0)
  _141 = int(torch.mul_(result11, element52))
  x20 = torch.reshape(x19, [_116, _138, _135, _136, _137])
  x21 = torch.permute(x20, [0, 2, 3, 1, 4])
  out2 = torch.reshape(x21, [_139, _140, _141])
  gate0 = torch.sigmoid_((out_proj0).forward(input1, ))
  feat_local_added0 = torch.mul(out2, gate0)
  _142 = ops.prim.NumToTensor(torch.size(single_repr2, 2))
  _143 = int(_142)
  feat_repr2 = torch.layer_norm(torch.to(single_repr2, 6), [_143], None, None, 0.10000000000000001)
  _144 = torch.chunk((lin_s_merged1).forward(input1, ), 2, -1)
  scale2, shift2, = _144
  _145 = torch.mul(feat_repr2, torch.add(scale2, CONSTANTS.c0))
  input6 = torch.add(_145, shift2)
  _146 = (linear_a_nobias_double0).forward(input6, )
  input7, a20, = torch.chunk(_146, 2, -1)
  input8 = torch.mul(torch.silu(input7), a20)
  _147 = (linear_s_biasinit_m20).forward(input1, )
  feat_trans_added0 = torch.mul(torch.sigmoid(_147), (linear_b_nobias0).forward(input8, ))
  _148 = torch.add(single_repr2, feat_trans_added0)
  single_repr3 = torch.add(_148, feat_local_added0)
  _149 = torch.bitwise_not(torch.unsqueeze(single_mask, -1))
  single_repr4 = torch.masked_fill(single_repr3, _149, 0.)
  _150 = [torch.to(_57, 15), torch.to(_60, 15)]
  value1 = torch.einsum("b l q k c, h c -> b h l q k", _150)
  element54 = ops.prim.NumToTensor(torch.size(block_pair_mask, 0))
  element55 = ops.prim.NumToTensor(torch.size(block_pair_mask, 1))
  element56 = ops.prim.NumToTensor(torch.size(block_pair_mask, 2))
  element57 = ops.prim.NumToTensor(torch.size(block_pair_mask, 3))
  _151 = int(torch.mul(element54, CONSTANTS.c0))
  _152 = int(torch.mul(element55, CONSTANTS.c0))
  _153 = int(torch.mul(element56, CONSTANTS.c0))
  _154 = int(torch.mul(element57, CONSTANTS.c0))
  mask1 = torch.reshape(block_pair_mask, [_151, 1, _152, _153, _154])
  blocked_pair_bias1 = torch.masked_fill(value1, torch.bitwise_not(mask1), -10000)
  _155 = ops.prim.NumToTensor(torch.size(single_repr4, 2))
  _156 = int(_155)
  feat_repr3 = torch.layer_norm(torch.to(single_repr4, 6), [_156], None, None, 0.10000000000000001)
  _157 = torch.chunk((lin_s_merged0).forward(input1, ), 2, -1)
  scale3, shift3, = _157
  _158 = torch.mul(feat_repr3, torch.add(scale3, CONSTANTS.c0))
  _159 = torch.add(_158, shift3)
  element58 = ops.prim.NumToTensor(torch.size(blocked_pair_bias1, 0))
  _160 = int(element58)
  _161 = int(element58)
  dim3 = ops.prim.NumToTensor(torch.size(blocked_pair_bias1, 1))
  _162 = torch.unbind((to_qkv).forward(_159, ))
  q3, k3, v3, = _162
  element59 = ops.prim.NumToTensor(torch.size(q_bias, 1))
  result12 = torch.mul(element58, CONSTANTS.c0)
  _163 = int(torch.mul_(result12, dim3))
  _164 = int(torch.mul(element59, CONSTANTS.c0))
  x22 = torch.unsqueeze(q_bias, 0)
  x23 = torch.expand(x22, [_161, -1, -1])
  x24 = torch.add(q3, torch.reshape(x23, [_163, 1, _164]))
  element60 = ops.prim.NumToTensor(torch.size(blocked_pair_bias1, 2))
  _165 = int(element60)
  dim4 = ops.prim.NumToTensor(torch.size(blocked_pair_bias1, 3))
  _166 = int(dim4)
  element61 = ops.prim.NumToTensor(torch.size(x24, 0))
  _167 = int(element61)
  element62 = ops.prim.NumToTensor(torch.size(x24, 2))
  q4 = torch.reshape(x24, [_167, _165, _166, int(element62)])
  _168 = torch.slice(k3, 0, 0, 9223372036854775807)
  _169 = torch.slice(_168, 2, 0, 9223372036854775807)
  _170 = annotate(List[Optional[Tensor]], [None, kv_idx])
  k4 = torch.index(_169, _170)
  _171 = torch.slice(v3, 0, 0, 9223372036854775807)
  _172 = torch.slice(_171, 2, 0, 9223372036854775807)
  _173 = annotate(List[Optional[Tensor]], [None, kv_idx])
  v4 = torch.index(_172, _173)
  element63 = ops.prim.NumToTensor(torch.size(blocked_pair_bias1, 0))
  element64 = ops.prim.NumToTensor(torch.size(blocked_pair_bias1, 1))
  element65 = ops.prim.NumToTensor(torch.size(blocked_pair_bias1, 2))
  element66 = ops.prim.NumToTensor(torch.size(blocked_pair_bias1, 3))
  element67 = ops.prim.NumToTensor(torch.size(blocked_pair_bias1, 4))
  result13 = torch.mul(element63, CONSTANTS.c0)
  _174 = int(torch.mul_(result13, element64))
  _175 = int(torch.mul(element65, CONSTANTS.c0))
  _176 = int(torch.mul(element66, CONSTANTS.c0))
  _177 = int(torch.mul(element67, CONSTANTS.c0))
  attn_mask1 = torch.reshape(blocked_pair_bias1, [_174, _175, _176, _177])
  x25 = torch.scaled_dot_product_attention(torch.to(q4, 15), k4, v4, attn_mask1)
  _178 = ops.prim.NumToTensor(torch.size(x25, 0))
  element68 = ops.prim.NumToTensor(torch.size(x25, 1))
  _179 = int(element68)
  element69 = ops.prim.NumToTensor(torch.size(x25, 2))
  _180 = int(element69)
  element70 = ops.prim.NumToTensor(torch.size(x25, 3))
  _181 = int(element70)
  other2 = torch.mul(element58, CONSTANTS.c0)
  element71 = torch.floor_divide(_178, other2)
  _182 = int(element71)
  _183 = int(torch.mul(element58, CONSTANTS.c0))
  result14 = torch.mul(element68, CONSTANTS.c0)
  _184 = int(torch.mul_(result14, element69))
  result15 = torch.mul(element71, CONSTANTS.c0)
  _185 = int(torch.mul_(result15, element70))
  x26 = torch.reshape(x25, [_160, _182, _179, _180, _181])
  x27 = torch.permute(x26, [0, 2, 3, 1, 4])
  out3 = torch.reshape(x27, [_183, _184, _185])
  gate1 = torch.sigmoid_((out_proj).forward(input1, ))
  feat_local_added1 = torch.mul(out3, gate1)
  _186 = ops.prim.NumToTensor(torch.size(single_repr4, 2))
  _187 = int(_186)
  feat_repr4 = torch.layer_norm(torch.to(single_repr4, 6), [_187], None, None, 0.10000000000000001)
  _188 = torch.chunk((lin_s_merged).forward(input1, ), 2, -1)
  scale4, shift4, = _188
  _189 = torch.mul(feat_repr4, torch.add(scale4, CONSTANTS.c0))
  input9 = torch.add(_189, shift4)
  _190 = (linear_a_nobias_double).forward(input9, )
  input10, a21, = torch.chunk(_190, 2, -1)
  input11 = torch.mul(torch.silu(input10), a21)
  _191 = (linear_s_biasinit_m2).forward(input1, )
  feat_trans_added1 = torch.mul(torch.sigmoid(_191), (linear_b_nobias).forward(input11, ))
  _192 = torch.add(single_repr4, feat_trans_added1)
  x28 = torch.add(_192, feat_local_added1)
  _193 = ops.prim.NumToTensor(torch.size(x28, 0))
  element72 = ops.prim.NumToTensor(torch.size(x28, 1))
  _194 = int(element72)
  element73 = ops.prim.NumToTensor(torch.size(x28, 2))
  _195 = int(element73)
  element74 = torch.floor_divide(_193, CONSTANTS.c0)
  input12 = torch.reshape(x28, [int(element74), 1, _194, _195])
  _196 = (to_token_single).forward(input12, )
  element75 = ops.prim.NumToTensor(torch.size(_196, 0))
  element76 = ops.prim.NumToTensor(torch.size(_196, 1))
  element77 = ops.prim.NumToTensor(torch.size(_196, 2))
  element78 = ops.prim.NumToTensor(torch.size(_196, 3))
  result16 = torch.mul(element75, CONSTANTS.c0)
  _197 = int(torch.mul_(result16, element76))
  _198 = int(torch.mul(element77, CONSTANTS.c0))
  _199 = int(torch.mul(element78, CONSTANTS.c0))
  atom_single_repr0 = torch.reshape(_196, [_197, _198, _199])
  element79 = ops.prim.NumToTensor(torch.size(atom_single_mask, 0))
  element80 = ops.prim.NumToTensor(torch.size(atom_single_mask, 1))
  result17 = torch.mul(element79, CONSTANTS.c0)
  _200 = int(torch.mul_(result17, CONSTANTS.c0))
  _201 = int(torch.mul(element80, CONSTANTS.c0))
  x29 = torch.unsqueeze(atom_single_mask, 1)
  x30 = torch.expand(x29, [-1, 1, -1])
  atom_single_mask0 = torch.reshape(x30, [_200, _201])
  element81 = ops.prim.NumToTensor(torch.size(atom_token_indices, 0))
  element82 = ops.prim.NumToTensor(torch.size(atom_token_indices, 1))
  result18 = torch.mul(element81, CONSTANTS.c0)
  _202 = int(torch.mul_(result18, CONSTANTS.c0))
  _203 = int(torch.mul(element82, CONSTANTS.c0))
  x31 = torch.unsqueeze(atom_token_indices, 1)
  x32 = torch.expand(x31, [-1, 1, -1])
  atom_token_indices0 = torch.reshape(x32, [_202, _203])
  x33 = torch.to(atom_token_indices0, 4)
  _204 = ops.prim.NumToTensor(torch.size(atom_single_repr0, 0))
  _205 = int(_204)
  _206 = ops.prim.NumToTensor(torch.size(atom_single_repr0, 2))
  pooled_repr = torch.new_zeros(atom_single_repr0, [_205, _7, int(_206)], dtype=None, layout=None, device=None, pin_memory=False)
  _207 = ops.prim.NumToTensor(torch.size(atom_single_repr0, 0))
  pooled_mask = torch.new_zeros(atom_single_repr0, [int(_207), _9], dtype=None, layout=None, device=None, pin_memory=False)
  element83 = ops.prim.NumToTensor(torch.size(atom_single_repr0, 2))
  _208 = int(element83)
  x34 = torch.unsqueeze(x33, 2)
  sum_token_indices = torch.expand(x34, [-1, -1, _208])
  _209 = torch.unsqueeze(atom_single_mask0, -1)
  atom_single_repr1 = torch.mul(atom_single_repr0, _209)
  pooled_repr0 = torch.scatter_reduce(pooled_repr, 1, sum_token_indices, atom_single_repr1, "sum")
  pooled_mask0 = torch.scatter_reduce(pooled_mask, 1, x33, torch.to(atom_single_mask0, 15), "sum")
  _210 = torch.clamp(torch.unsqueeze(pooled_mask0, -1), 1)
  x35 = torch.div(pooled_repr0, _210)
  _211 = ops.prim.NumToTensor(torch.size(x35, 0))
  element84 = ops.prim.NumToTensor(torch.size(x35, 1))
  _212 = int(element84)
  element85 = ops.prim.NumToTensor(torch.size(x35, 2))
  _213 = int(element85)
  element86 = torch.floor_divide(_211, CONSTANTS.c0)
  x36 = torch.reshape(x35, [int(element86), 1, _212, _213])
  element87 = ops.prim.NumToTensor(torch.size(x36, 0))
  element88 = ops.prim.NumToTensor(torch.size(x36, 1))
  element89 = ops.prim.NumToTensor(torch.size(x36, 2))
  element90 = ops.prim.NumToTensor(torch.size(x36, 3))
  result19 = torch.mul(element87, CONSTANTS.c0)
  _214 = int(torch.mul_(result19, element88))
  _215 = int(torch.mul(element89, CONSTANTS.c0))
  _216 = int(torch.mul(element90, CONSTANTS.c0))
  pooled_token_single_repr = torch.reshape(x36, [_214, _215, _216])
  _217 = [pooled_token_single_repr, token_single_input_feats]
  input13 = torch.cat(_217, -1)
  _218 = (token_single_proj_in_structure).forward(input13, )
  _219 = (token_single_proj_in_trunk).forward(input13, )
  _220 = (token_single_to_token_pair_outer_sum_proj).forward(_219, )
  x37, x38, = torch.chunk(_220, 2, -1)
  element91 = ops.prim.NumToTensor(torch.size(x37, 0))
  element92 = ops.prim.NumToTensor(torch.size(x37, 1))
  element93 = ops.prim.NumToTensor(torch.size(x37, 2))
  _221 = int(torch.mul(element91, CONSTANTS.c0))
  _222 = int(torch.mul(element92, CONSTANTS.c0))
  _223 = int(torch.mul(element93, CONSTANTS.c0))
  _224 = torch.reshape(x37, [_221, _222, 1, _223])
  _225 = torch.add(token_pair_input_feats, _224)
  element94 = ops.prim.NumToTensor(torch.size(x38, 0))
  element95 = ops.prim.NumToTensor(torch.size(x38, 1))
  element96 = ops.prim.NumToTensor(torch.size(x38, 2))
  _226 = int(torch.mul(element94, CONSTANTS.c0))
  _227 = int(torch.mul(element95, CONSTANTS.c0))
  _228 = int(torch.mul(element96, CONSTANTS.c0))
  _229 = torch.reshape(x38, [_226, 1, _227, _228])
  input14 = torch.add(_225, _229)
  _230 = (token_pair_proj_in_trunk).forward(input14, )
  return (_219, _218, _230)
